### ISSUE TITLE
Can't bind to a local IP Address

### ISSUE THREAD

**Issue by makorne** [EAimTY/socks5-server#7]
Hi!
Thank you for your great crates!

I tried to start your socks5 on a server with two ip addreses.
And while I start it with ip1 the httpbin.org/ip shows the ip0 - the main server ip0.

How to bind socks5 server to  ip1?
Like it is in [reqwest](https://docs.rs/reqwest/latest/src/reqwest/async_impl/client.rs.html#1018-1024)

**Comment by mllken** [comment]
For outgoing client connections, you can use tokio's TcpSocket to bind to a specifc IP address and then call it's connect() method:
https://docs.rs/tokio/latest/tokio/net/struct.TcpSocket.html#method.bind

Use this instead of TcpStream::connect in your socks server client handler.

**Comment by makorne** [comment]
Thank you!!
